### PR TITLE
Moving action generator tests to use filetest

### PR DESCRIPTION
**Pull request by apaganobeleno**
@markbates according to #407 this one moves actions generator tests to use filetest instead of go tests.

### CODE REVIEW

**Comment by markbates** [comment]
I'm getting the following error:

```
--- FAIL: TestAppendRoute (0.00s)
        Error Trace:    helpers_test.go:82
	Error:      	Not equal: 
	            	expected: "package actions\n\nimport (\n\t\"os\"\n\n\t\"github.com/gobuffalo/buffalo\"\n\t\"github.com/gobuffalo/buffalo/examples/json-crud/models\"\n\t\"github.com/gobuffalo/buffalo/middleware\"\n\t\"github.com/markbates/going/defaults\"\n)\n\nvar ENV = defaults.String(os.Getenv(\"GO_ENV\"), \"development\")\nvar app *buffalo.App\nfunc App() *buffalo.App {\n\tif app == nil {\n\t\tapp = buffalo.Automatic(buffalo.Options{\n\t\t\tEnv: ENV,\n\t\t})\n\n\t\tapp.Use(middleware.SetContentType(\"application/json\"))\n\t\tapp.Use(middleware.PopTransaction(models.DB))\n\n\t\tapp.Use(findUserMW)\n\t\tapp.GET(\"/users\", UsersList)\n\t\tapp.GET(\"/new/route\", UserCoolHandler)\n\t}\n\n\treturn app\n}"
```

**Comment by apaganobeleno** [comment]
yes, sorry @markbates, fixing that with my latest commit. i also sent [this PR](https://github.com/markbates/filetest/pull/6/files) to filetest so it can now do contains with a count.

**Comment by markbates** [comment]
@apaganobeleno the tests are so much faster now!! thank you!!

**Comment by apaganobeleno** [comment]
👍 still need to work on other test cases, i'll send another PR later after this one merges.

**Pull request merged**
