### PR TITLE
Add codecov.io badge

### PR DESCRIPTION
**Pull request by AlekSi**
There is no coverage information for `master` branch yet, that's why badge says "unknown" for now.

`.codecov.yml` format is documented [here](https://docs.codecov.io/docs/codecov-yaml). See also next pages; specifically, [here](https://docs.codecov.io/docs/coverage-configuration) for what "range" means.

### CODE REVIEW

**Comment by AlekSi** [comment]
btw, @markbates, you can add `--squash` to `docker build` for `gobuffalo/buffalo:development` image to make it significantly smaller.

**Comment by markbates** [comment]
@AlekSi if you know how to do that on hub.docker.com please let me know. That's where we build the images.

**Comment by AlekSi** [comment]
Looks like it is not possible: https://github.com/docker/hub-feedback/issues/955 One workaround is to use multi-stage builds which are supported. Another one is to rebuild this image somewhere else.

**Comment by markbates** [comment]
@AlekSi feel free and take a crack at making it smaller.

**Pull request merged**
