### PR TITLE
added Godoc documentation for tokenauth middleware

### LINKED ISSUE #1056: The tokenauth middleware needs to be documented
The [tokenauth middleware](https://github.com/gobuffalo/buffalo/tree/master/middleware/tokenauth) is currently not documented. The [tests](https://github.com/gobuffalo/buffalo/blob/master/middleware/tokenauth/tokenauth_test.go) can kind of suffice, but not really. There is [this blog post](https://medium.com/@francescodonzello/jwt-and-go-buffalo-4cce3ae73723) linked on the website, but that was written before tokenauth middleware was merged, however, uses the same library, which is unlikely to be coincidental. 

Unless someone takes this on, I might write this. I'm opening an issue so it's tracked.

### PR DESCRIPTION
**Pull request by Shivakishore14**
resolves #1056

### CODE REVIEW

**Comment by robbyoconnor** [comment]
I have concerns about this library. I would prefer we used either [this one](https://github.com/gbrlsnchs/jwt) or [this one](https://github.com/SermoDigital/jose), the latter actually implemented more than just JWT.

**Comment by robbyoconnor** [comment]
I'm actually using the latter in my app and rolling my own middleware.

**Comment by Shivakishore14** [comment]
@markbates this is a documentation only PR. can you review this and merge, I think this will be helpful for others till robbyoconnor rolls out his version of middleware.

**Comment by markbates** [comment]
Thanks!

**Pull request merged**
