### PR TITLE
Add Homebrew goreleaser configuration

### LINKED ISSUE #1286: Homebrew formula created
I've created a tap and [homebrew](https://brew.sh/) formula for Buffalo: https://github.com/duffn/homebrew-buffalo

It can be installed as such:
```
% brew install duffn/buffalo/buffalo                                                                                                                1 ↵
==> Tapping duffn/buffalo
Cloning into '/usr/local/Homebrew/Library/Taps/duffn/homebrew-buffalo'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Tapped 1 formula (30 files, 23.3KB).
==> Installing buffalo from duffn/buffalo
==> Downloading https://github.com/gobuffalo/buffalo/releases/download/v0.12.6/buffalo_0.12.6_darwin_amd64.tar.gz
🍺  /usr/local/Cellar/buffalo/0.12.6: 5 files, 12.2MB, built in 2 seconds
```

I'm happy to maintain it as new versions are released or transfer it to the gobuffalo organization if that is preferred. I can also add to the docs as an installation option.

### PR DESCRIPTION
**Pull request by duffn**
This is the Homebrew configuration for goreleaser.

**Notes**
- This assumes that there will be a `gobuffalo/homebrew-tap` repository to serve as the Homebrew tap and to hold the formula.
- I've not used goreleaser before, so am unsure how to test that this functions correctly.

Closes #1286

### CODE REVIEW

**Comment by markbates** [comment]
@duffn https://github.com/gobuffalo/homebrew-tap - I've given you access. when that's all set up we can merge this! :)

**Comment by duffn** [comment]
Should be good to go, but we'll see what goreleaser does. I'll update the docs.

**Comment by markbates** [comment]
@duffn thanks. since I know not of how home-brew works, do we also need to manually update the `gobuffalo/homebrew-tap` or will goreleaser do it for us? and if we have to do it manually, at which stage in the process should we do something? sorry for all the questions.

**Comment by duffn** [comment]
I've never used goreleaser with Homebrew before, but looking at the documentation, it should update the repo automatically when a new release is created.

Here's goreleaser doing it themselves: https://github.com/goreleaser/homebrew-tap/commit/0bc30f7c5e868726c8665c910c714f530cfe12fc

If it doesn't work the first time for whatever reason, I can update the `homebrew-tap` repo manually so installs still work and fix the `.goreleaser.yml` until we do get it to work.

**Pull request merged**
