### PR TITLE
Add test for template partial rendering with a local variable.

### PR DESCRIPTION
**Pull request by ajcollins**
Hi Mark,

After reading the documentation on partial rendering (https://gobuffalo.io/en/docs/partials#local-context) I expected local and global variables to be merged. This doesn't seem to happen at present. That may be the desired behaviour?

This adds a failing test case. It could be combined with the existing test case, depending on your preferred approach.

I've created a candidate fix in `plush/compiler.go` for which I'll submit an MR for review.

Best wishes,

Alex

### CODE REVIEW

**Comment by markbates** [comment]
I think the correct fix is here in the buffalo repo, instead of the plush repo, since the `partial` helper is defined in buffalo. https://github.com/gobuffalo/buffalo/blob/master/render/template.go#L43

**Comment by ajcollins** [comment]
That was what I'd originally hoped, but I couldn't see a way for the partial helper to access the required context information: since plush is responsible for binding the arguments to the function call. Perhaps I'm missing something?

Happy to update the PR if you can suggest where to access this (or change how it's accessed).

**Comment by markbates** [comment]
I think you need to start here https://github.com/gobuffalo/buffalo/blob/master/render/template.go#L29 capture the original `Data` and hold onto it in the struct. Then in `partial` you would want to create a new map that merges the renderer Data and the partial's data.

**Comment by ajcollins** [comment]
Snap! I'll do that then - thanks.

**Pull request closed without merging**
