### PR TITLE
added input/status checks, testcases, and comments for road-to-v1

### PR DESCRIPTION
**Pull request by sio4**
Improved the simple worker:

* Added input/status checks for
  * `Register()`, if the name and handler are defined correctly
  * `Perform()` and `PerformIn()`, if the worker's context was already canceled to prevent job submission
* Added wait group count for delayed jobs (PerformIn)
* Added locking in `Stop()` to prevent job submission when stopping
* Added comments for the road-to-v1 (#2242)

(This PR was started for #2241)

### CODE REVIEW

**Comment by sio4** [comment]
This PR was started for #2241 but the root cause of the issue was not here. However, this PR will make Simple Worker more reliable.

**Review by paganotoni — APPROVED** [review]

**Comment by paganotoni** [comment]
Thanks for this one @sio4

**Comment by sio4** [comment]
Thanks!

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
Thanks @sio4, looks good to me!

**Pull request merged**
