### PR TITLE
Refactor CI config generator

### PR DESCRIPTION
**Pull request by stanislas-m**
* Add MySQL conf for Travis setup.
* Extract CI generator, so it can be reused (so we can generate the CI conf after creating the app).

### CODE REVIEW

**Comment by markbates** [comment]
I’ll check this out later, but what are your thoughts on moving these out into plugins? Would be faster to iterate on, thin out core a bit more, and set a precedent for using plugins for stuff like this. Thoughts?

**Comment by paganotoni** [comment]
Sorry to jump in here but I love the idea of moving CI things out to be plugins

**Comment by stanislas-m** [comment]
That seems to be a good idea, but it means we'll remove the option from the `new` command, right?

**Comment by markbates** [comment]
Eventually we have to lose the flag, but we migrate by putting out the plugins first and then updating the flag to go get and run the plugin and issue a deprecation warning saying use the plugin in the future.

**Comment by markbates** [comment]
@stanislas-m I'm closing this since we both agree it should move to a plugin.

**Comment by stanislas-m** [comment]
Sure, np.

**Pull request closed without merging**
