### PR TITLE
"Fix" Issue #841

### PR DESCRIPTION
**Pull request by Zarkopafilis**
I want to make sure if this should be the proper way to set the development environment for the build, in order to procceed with testing & possible mistake corrections.

A new environment flag is registered and defaulted to "development".
Then, on **bin.go**, its passed to envy (not persisted to the underlying environment), in order to procceed to **exec.go** without changing function signatures.

The value is retrieved from envy and appended in the Env slice of **exec.Cmd** so it can be used instead of the default one on the actual command execution step.

https://github.com/gobuffalo/buffalo/issues/841

### CODE REVIEW

**Comment by markbates** [comment]
Thanks for looking into, unfortunately it doesn't solve the issue of #841. The behind that ticket is the binary that built from running `buffalo build` can be set to run in an environment other than development. This means the binary needs to get the environment "burnt" into it. This PR simply sets the requested environment of the `buffalo build` command, and unfortunately, not the finish binary. Does that make sense?

Also, this line:

```go
cmd.Env = envy.Environ()
```

breaks Windows, which is why it was removed and caused the problem of #845. When implemented #841 won't fix #845 unfortunately.

**Comment by markbates** [comment]
The good news is, you're very close to the actual implementation. :) I was thinking that adding a line to the `main.go` file that gets generated as part of the build process could contain something like:

```go
func init() {
  envy.Set("GO_ENV", "<environment>")
}
```

That's might be enough to do it.

**Comment by Zarkopafilis** [comment]
Should it be just `Set` or `MustSet` (Try to persist to the host as well)?

**Comment by markbates** [comment]
@Zarkopafilis I'm closing this PR in favor of #850 because GitHub won't let me push a commit to this PR.

When testing this I found that it still wasn't working. I dug deeper and found that the place that we wanted to set the ENV var was too late. The `actions` package was already loaded by that point, so the `actions.ENV` was already set.

In order to get it to load properly, I moved the setting of the ENV var from the `main` package to the `a` package which gets loaded __before__ `actions`. That solved the problem. :)

Thanks for taking point on this.

**Pull request closed without merging**
