### PR TITLE
Adding "BUFFALO_PLUGIN_TIMEOUT" option.

### LINKED ISSUE #1103: Plugin Load Timing Out
## Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. Develop on Windows
  1. Work in an office with a despotic and ridiculous IT department, that enforces super invasive scanning everytime one runs a program.
  1. Install a Buffalo Plugin
  1. Run any buffalo command.

## Expected Behavior

Plugins should all load as expected.

## Actual Behavior

Plugins sometimes take more than a second to load, and Buffalo gives up on them. I've modified my local copy of buffalo to timeout after 10 seconds, and plugins always load. When I added a test to see how long it took, most plugins loaded in about 1.5 seconds.

What I'd like to see is a way to parameterize how long before I give up on loading plugins. I can submit a PR to fix this.

## Info

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>
(I know, I know, I'll upgrade to v0.12.* later today)

?[31mERRO?[0m[0001] [PLUGIN] error loading plugin D:\Users\marstr\go\bin\buffalo-azure.exe: exit status 1

?[31mERRO?[0m[0002] [PLUGIN] error loading plugin D:\Users\marstr\go\bin\buffalo-goth.exe: exit status 1

### Buffalo Version
v0.11.0

### App Information
Pwd=D:\Users\marstr\go\src\github.com\gobuffalo\buffalo
Root=D:\Users\marstr\go\src\github.com\gobuffalo\buffalo
GoPath=D:\Users\marstr\go
Name=buffalo
Bin=bin\buffalo.exe
PackagePkg=github.com/gobuffalo/buffalo
ActionsPkg=github.com/gobuffalo/buffalo/actions
ModelsPkg=github.com/gobuffalo/buffalo/models
GriftsPkg=github.com/gobuffalo/buffalo/grifts
VCS=git
WithPop=false
WithDep=true
WithWebpack=false
WithYarn=false
WithDocker=true
WithGrifts=true

### Go Version
go version go1.9.2 windows/amd64

### Go Env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Users\marstr\go
set GORACE=
set GOROOT=C:\Program Files\Go
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\marstr\AppData\Local\Temp\go-build365257475=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### Node Version
v8.9.1

### NPM Version
5.7.1

   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.5.1 → 6.1.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

### Yarn Version
1.6.0

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
SQLite Not Found

### Dep Version
dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.9.2
 go compiler : gc
 platform    : windows/amd64
 features    : ImportDuringSolve=false

### Dep Status

</details>

### PR DESCRIPTION
**Pull request by marstr**
Doing so lets users configure how long buffalo will wait while trying to load a plugin. In particular, this is helping on my box where security policies are setup in a manner that frequently has plugins taking 1.5 seconds to load.

Fixes #1103

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Update the docs as well?

**Comment by marstr** [comment]
Sure thing, I'll add a test too.

**Comment by marstr** [comment]
@robbyoconnor, I believe I'm ready for review. In terms of adding documentation, I only found one instance of the text "BUFFALO_PLUGIN_PATH" in the comments of this repository. If there's somewhere else I should add documentation, just let me know.

**Comment by robbyoconnor** [comment]
The gobuffalo site is the way to for that...otherwise Godocs are completely valid as well.

**Comment by marstr** [comment]
I believe I've documented in all of the relevant places. :)

**Comment by robbyoconnor** [comment]
Exactly.. you're good :)

**Comment by marstr** [comment]
Just reach out if there's anything else y'all want from me in order to merge. :)

**Comment by marstr** [comment]
> I think this should probably be a flag. 

I hear you, but given that plugin loading is something sort of universally slow on my machine I'd like it to be something more ambient than a flag that I have to specify every-time I run Buffalo. There are a lot of ways we could achieve that though. :)

> I'm also wondering the flag should be for timeout or to skip the plugin loading entirely.

Why not both? I think both are probably valid use-cases. I'd be happy to throw in flag '--skip-plugins' or another environement variable called 'BUFFALO_SKIP_PLUGINS'.

**Comment by marstr** [comment]
Thinking about it more, I think I understand what you're getting at:
- Loading plugins is just a perf tax to pay if someone is running a non-plugin related command.
- Making that tax larger all the time will be annoying.
- Trying to load plugins lazily is probably a big enough change that it is outside the scope of this PR. (Definitely somthing I'd be interested in helping with in the future though! Load plugins only when there was a command miss, then show usage only if it's still a miss. How awesome would that be?)

From the other side's perspective:
- Plugins never load in under a second on my machine. (Setting `BUFFALO_PLUGIN_PATH` helped, but not quite enough)
- Specifying a flag to say I want to give plugins 2s to load is annoying to do everytime, but having it load from either an environment variable could work.
- Having both an ambient "give plugins two seconds to run" option, and a `--skip-plugins` would allow me to speed up operations opportunistically when I was annoyed by waiting.

**Comment by marstr** [comment]
@markbates, done. :)

**Comment by marstr** [comment]
Hooray!

**Pull request merged**
