### PR TITLE
Less ugly production error page

### PR DESCRIPTION
**Pull request by paganotoni**
Given what we discussed in #930 I decided to start with this simple design for the error page, it adds some styling to it so we can have a better-looking error page for production:

error-page

(nothing fancy for now)

@markbates @stanislas-m sorry for the delay with this one, I think we can iterate from this first version, LMK if you guys want to change copy or any style you don't like.

### CODE REVIEW

**Comment by markbates** [comment]
Considering that looks a million times better than what we have now, I’m happy!

**Comment by stanislas-m** [comment]
@paganotoni That's way better! :+1:  Is it possible to have a different text, at least for the 404 Not Found page? "Something went wrong" is not the kind of error you're used to see for a page not found, in my head it sounds I've broken something.

**Comment by paganotoni** [comment]
@stanislas-m i like that idea, i'll add that into this PR, agree that its a bit odd to see an error when its actually a 404.

**Comment by paganotoni** [comment]
@stanislas-m  not-found

**Comment by stanislas-m** [comment]
@paganotoni I'm not sure the sentence about the app owner is necessary, but overall that's great! (404 errors are really common, and as an app owner I'll probably look at the logs for server errors, not 404 ones.)

**Comment by paganotoni** [comment]
@stanislas-m @markbates I'm removing the WIP, added another flavor for 404 as @stanislas-m mentioned, give it a shot and let me know :)

**Comment by robbyoconnor** [comment]
I vote we use https://http.cat photos :D

**Comment by paganotoni** [comment]
@markbates this one is ready to be merged.

**Pull request merged**
