### PR TITLE
Feature/improved error reporting in production

### PR DESCRIPTION
**Pull request by StefanDorresteijn**
This fixes https://github.com/gobuffalo/buffalo/issues/2107

### CODE REVIEW

**Comment by paganotoni** [comment]
Hey @StefanDorresteijn, thanks for putting this PR together. Could you please add some test cases for the changes in here?

**Comment by StefanDorresteijn** [comment]
Test code was added and I've adjusted my code to make sure it passes @paganotoni

**Review by paganotoni — APPROVED** [review]

**Comment by StefanDorresteijn** [comment]
Anything you guys need from me to get this merged?

**Comment by paganotoni** [comment]
Ups, thanks for following up @StefanDorresteijn. Nothing else needed. Thank you!

**Pull request merged**
