### PR TITLE
First Attempt at #105 

### PR DESCRIPTION
**Pull request by apaganobeleno**
hi @markbates i've implemented the first test scenario for the route appender (#105) to the `app.go`, it still assumes some things, but wanted to keep you posted and gather some feedback.

### CODE REVIEW

**Comment by markbates** [comment]
I'll take a look at this after I've had some coffee this morning.

**Comment by markbates** [comment]
It would be nice if we could make this a bit more generic. I would like to be able to move this:

https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/generate/resource.go#L73

Into app.go as well. Perhaps it takes a string to insert into the file, or function or something. Just spit balling here.

**Comment by apaganobeleno** [comment]
@markbates ok just changed it to receive the expression you want to add inside the block, would be great if you provide me a few other examples, for now i'm assuming everything will go inside the `if app == null` block.

**Comment by apaganobeleno** [comment]
@markbates does this last change helps ?

**Comment by markbates** [comment]
What is the state of this PR? I'd love to merge it in and use it for the next release.

**Comment by apaganobeleno** [comment]
@markbates this one is ready to be used, i also would like to use it for the actions generator.

**Pull request merged**
