### PR TITLE
Add phtread library to build flags

### PR DESCRIPTION
**Pull request by imcsk8**
When building buffalo with sqlite support on Linux there's
a compilation error since the pthread library is not explicitly
linked.

### CODE REVIEW

**Comment by markbates** [comment]
@imcsk8 can you please open this PR against the `development` branch? Thank you.

**Comment by imcsk8** [comment]
Yes, no problem

**Comment by imcsk8** [comment]
- Fedora 28
- go version go1.10.3 gccgo (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5) linux/amd64
- followed buffalo instructions for using sqlite

**Comment by stanislas-m** [comment]
I'm sorry, I tried to reproduce on Fedora and it works well if you installed the required dependencies (make sure the package containing lib pthread is installed too). The sqlite3 driver already have the required configuration, so there's no point adding it here: https://github.com/mattn/go-sqlite3/commit/e688f0a8eb3db91c7cd1bf0925bac5bdf951a553

**Pull request closed without merging**
