### PR TITLE
Not the plural.

### PR DESCRIPTION
**Pull request by leo-baltus**
https://github.com/golang/go/wiki/Modules#what-are-some-general-things-i-can-spot-check-if-i-am-seeing-a-problem

### CODE REVIEW

**Comment by leo-baltus** [comment]
Anything I can do?

**Comment by paganotoni** [comment]
@leo-baltus It seems there is still a conflict with development. I suggest you create a new branch from development and apply the change there, then send a PR from that branch into development.

**Comment by leo-baltus** [comment]
sorry, thats just too many hoops to jump through. It's just a typo, you get the idea.

**Comment by paganotoni** [comment]
Allright. Are you ok if I send another PR with this change?

**Comment by paganotoni** [comment]
@leo-baltus I created #1786. Closing this one.

**Pull request closed without merging**
