### PR TITLE
Adds Test cases for the travis/none ci-provider generation

### PR DESCRIPTION
**Pull request by apaganobeleno**
This PR adds some test cases for the --ci-provider flag, it covers the travis and none ci-providers but could serve as base for circle and other ci providers we integrate.

### CODE REVIEW

**Comment by markbates** [comment]
Out of curiosity, would this have been easier to test in the Dockerfile? That's meant for this sort of "integration" testing.

**Comment by apaganobeleno** [comment]
interesting, trying that alternative :)

**Comment by markbates** [comment]
@apaganobeleno https://github.com/markbates/filetest check that out. i think it's time buffalo does a better job of testing our generated files

**Comment by apaganobeleno** [comment]
@markbates sure, looking into it.

**Comment by apaganobeleno** [comment]
@markbates just added filetest check to the Dockerfile, LMK if thats the way you wpould expect me to use it, thanks for building it.

it would be good to add `notExist` and `notContains` to filetest.

**Comment by markbates** [comment]
@apaganobeleno how was `filetest` to use? this was the exact use case i had for it.

**Comment by apaganobeleno** [comment]
@markbates awesome, you're doing our life great every day! keep that up Sir.

**Comment by markbates** [comment]
lol. i just added `!contains` to the json spec https://github.com/markbates/filetest/commit/d5ee137bff89c615490bb85d040a9ab8e94b4aef

**Pull request merged**
