### PR TITLE
Task updating bootstrap

### PR DESCRIPTION
**Pull request by paganotoni**
This PR updates bootstrap version to pass on a security warning our repo currently has.

### CODE REVIEW

**Comment by stanislas-m** [comment]
@paganotoni Bootstrap 3 also needs to be updated to >=3.4.1. And this probably should be merged into master, since it's a security patch. :)

**Comment by paganotoni** [comment]
@markbates @stanislas-m closing this one and opening another one from master with packr2 files regenerated.

**Comment by markbates** [comment]
Please don’t. Merge this into development. I want to release a .1 in a week or so.

If you do it against master, you’ll also have to do it again development so the packr files are correct in both places.

-----------
Mark Bates

**Comment by markbates** [comment]
If you really want to release it on master quick, you’ll have to open 2 PRs for the packr files.

-----------
Mark Bates

**Comment by paganotoni** [comment]
@markbates i opened: https://github.com/gobuffalo/buffalo/pull/1604 to cover this one, its pointing development instead of master as you suggested.

**Pull request closed without merging**
