### PR TITLE
Resource default test generator #366

### PR DESCRIPTION
**Pull request by as27**

### CODE REVIEW

**Comment by markbates** [comment]
Need to remove `buffalo/buffalo2` from the PR

**Comment by markbates** [comment]
```bash
$ buffalo g resource post title body:nulls.Text


actions/posts_test.go:31: cannot use "A string for Body" (type string) as type nulls.String in field value
actions/posts_test.go:35: cannot use "Another string for Body" (type string) as type nulls.String in field value
actions/posts_test.go:70: cannot use "A value for Body" (type string) as type nulls.String in field value
actions/posts_test.go:115: cannot use "A value for Body" (type string) as type nulls.String in field value
actions/posts_test.go:137: cannot use "Initial value for Body" (type string) as type nulls.String in field value
actions/posts_test.go:147: cannot use "Changed value for Body" (type string) as type nulls.String in field value
```

**Comment by markbates** [comment]
We need to do a better job of filling in good random values for the models.

**Comment by as27** [comment]
> We need to do a better job of filling in good random values for the models.

@markbates yes you are right. 
But to handle all the logic inside the template is too much. I am going to write a helper for the template. First I would add this new helper inside `generate/resource.go` via `makr.Helper["createDefaultValue"] = ...`  after that the definition could move into `makr/helpers.go` or better into `pop`, because when there will be a new type inside `pop` no other package had to be changed. What do you think?

**Comment by markbates** [comment]
I'm thinking that a good "first pass" would be a comment above the struct in the test that says something like:

```go
func (as *ActionSuite) Test_TodosResource_List() {
	// TODO: fill-in "models.Todo{}" with appropriate test data
	todos := models.Todos{}
	for _, t := range todos {
		err := as.DB.Create(&t)
		as.NoError(err)
	}

	res := as.HTML("/todos").Get()
	body := res.Body.String()
	for _, t := range todos {
		as.Contains(body, fmt.Sprintf("<h2>%s</h2>", t.Title))
	}
}
```

or we could use a failure message:

```go
func (as *ActionSuite) Test_TodosResource_List() {
	as.FailNow(" TODO: fill-in 'models.Todo{}' with appropriate test data")
	todos := models.Todos{}
	for _, t := range todos {
		err := as.DB.Create(&t)
		as.NoError(err)
	}

	res := as.HTML("/todos").Get()
	body := res.Body.String()
	for _, t := range todos {
		as.Contains(body, fmt.Sprintf("<h2>%s</h2>", t.Title))
	}
}
```

That would be "good enough" for a first pass. 

As a second pass, I think it would be great to either find, or build, a tool that will take a struct (or slice) and generate random values for it's data.

```go
func (as *ActionSuite) Test_TodosResource_Create() {
	todo := &models.Todo{}
	somepackage.Fill(todo, somepackage.Options{
		"ID": {Skip: true},
		"Body": {Filler: func() interface{} {
			return "some body text"
		}},
	})
	/*
	values would be:
	todo.ID = ""
	todo.Body = "some body text"
	todo.Title = "asdfkjasdfjasdfkjsda"
	*/
	res := as.HTML("/todos").Post(todo)
	as.Equal(301, res.Code)
	as.Equal("/todos", res.Location())

	err := as.DB.First(todo)
	as.NoError(err)
	as.NotZero(todo.ID)
	as.NotZero(todo.CreatedAt)
	as.Equal("Learn Go", todo.Title)
}
```

**Comment by markbates** [comment]
Just started playing with it. So far, looks good. Noticed that there is a missing `.` in the error messages:

```
TODO: fill-in 'modelsPost{}' with appropriate test data
```

**Pull request closed without merging**
