### PR TITLE
[#193] adding line number to the Context#Get warning

### PR DESCRIPTION
**Pull request by apaganobeleno**
cc @markbates

### CODE REVIEW

**Comment by bscott** [comment]
@apaganobeleno I'm just catching up, why did we deprecate `context#get`

**Comment by apaganobeleno** [comment]
@bscott this is related with https://github.com/gobuffalo/buffalo/issues/153

**Comment by apaganobeleno** [comment]
@markbates something else this one needs ? better wording p.e. ?

**Comment by markbates** [comment]
@bscott i deprecated `Get` because I implemented the `context.Context` interface, and didn't see the need for both `Get` and `Value`. I prefer the name `Get`, but it seemed to silly to have both.

**Pull request merged**
