### PR TITLE
Makes our tests run on Go 1.7 and 1.8

### PR DESCRIPTION
**Pull request by apaganobeleno**
@markbates This PR makes our tests run against Go`1.7` and `1.8` you may notice i set it to be `1.8` instead of `latest` because on the [dockerhub](https://hub.docker.com/_/golang/) latest is 1.7.4 or latest stable.

### CODE REVIEW

**Comment by apaganobeleno** [comment]
Oh also this should make our build times faster given we're now skipping the travis installation since all we do for our tests runs inside the image we're building.

**Comment by markbates** [comment]
@apaganobeleno so how do i run `docker build .` locally now?

**Comment by markbates** [comment]
@apaganobeleno i made a change to have it run 1.7 locally, and, in theory, get changed in travis. let's see if that works!

**Comment by apaganobeleno** [comment]
Ah! Good one @markbates!

**Pull request merged**
