### PR TITLE
issue-35: readme generator

### PR DESCRIPTION
**Pull request by briandowns**

### CODE REVIEW

**Comment by markbates** [comment]
Definitely a good start. Some info on how to run, or test, a Buffalo app would be great. Maybe a link to http://gobuffalo.io, that sort of thing.

**Comment by briandowns** [comment]
Sounds good. Will add now.

**Comment by markbates** [comment]
Here's the README that Rails generates:

https://raw.githubusercontent.com/rails/rails/master/railties/lib/rails/generators/rails/app/templates/README.md

It's a little "bland", but not a bad start.

I'm thinking things like:

* link to buffalo docs
* link to pop/soda docs
* configuring the database.yml
* running buffalo dev
* running migrations
* running tests

that sort of thing. doesn't have to be perfect, we can keep adding to it over time.

thanks for tackling this!

**Comment by briandowns** [comment]
1.7 passed but NPM game up the ghost on master.

**Comment by briandowns** [comment]
Ok, that's better.

**Comment by markbates** [comment]
Thanks. Brian!

**Pull request merged**
