### PR TITLE
Named Routes implementation.

### PR DESCRIPTION
**Pull request by apaganobeleno**
This is my first attempt at supporting named routes as well as route helper functions available on the view, for more context please look into #210.

cc @markbates

### CODE REVIEW

**Comment by apaganobeleno** [comment]
@markbates i tried to look into other cases here, but seems this one should be ready and covers the 

```go
<%= usersPath({user_id: 1}) %>
```

Helpers function mode, LMK when you give it a shot, i'm looking forward for your feedback.

**Comment by markbates** [comment]
I went and added a users resource `buffalo g resource users` and I'm seeing some duplicate routes when I run `buffalo t routes`.

I'm guessing that something is putting them into the RouteList multiple times, not sure what though.

```
METHOD | PATH                  | NAME         | HANDLER
------ | ----                  | ----         | -------
DELETE | /users/{user_id}      | userPath     | github.com/gobuffalo/buffalo.(Resource).Destroy-fm
DELETE | /users/{user_id}      | userPath     | github.com/gobuffalo/buffalo.(Resource).Destroy-fm
GET    | /                     | rootPath     | github.com/markbates/coke/actions.HomeHandler
GET    | /users/new            | newUsersPath | github.com/gobuffalo/buffalo.(Resource).New-fm
GET    | /users/{user_id}/edit | userEditPath | github.com/gobuffalo/buffalo.(Resource).Edit-fm
POST   | /users                | usersPath    | github.com/gobuffalo/buffalo.(Resource).Create-fm
POST   | /users                | usersPath    | github.com/gobuffalo/buffalo.(Resource).Create-fm
PUT    | /users/{user_id}      | userPath     | github.com/gobuffalo/buffalo.(Resource).Update-fm
```

**Comment by markbates** [comment]
Also, wherever we should routing information we should show the helper function name.

Places I can't think of off the top of my head are the `routes` task, the `404` and `500` pages, and the generated `index.html` page.

**Comment by apaganobeleno** [comment]
thanks @markbates, i'll look into this one and be back soon, regards!

**Comment by apaganobeleno** [comment]
@markbates sorry on the delay with this one, busy times, but i'm so happy to be helping back, i think i've solved the dupes issue, also updated the templates as you mentioned.

On another topic, given on the resource there are some routes which has the same path, i took the audacity to add some of the routes names like the follows:

METHOD | PATH                 | NAME           | HANDLER
------ | ----                 | ----           | -------
DELETE | /user/{user_id}      | **userDeletePath** | github.com/gobuffalo/buffalo.(Resource).Destroy-fm
GET    | /user                | **userPath**       | github.com/gobuffalo/buffalo.(Resource).List-fm
GET    | /user/new            | **newUserPath**    | github.com/gobuffalo/buffalo.(Resource).New-fm
GET    | /user/{user_id}      | **userShowPath**       | github.com/gobuffalo/buffalo.(Resource).Show-fm
GET    | /user/{user_id}/edit | **userEditPath**   | github.com/gobuffalo/buffalo.(Resource).Edit-fm
POST   | /user                | **userCreatePath** | github.com/gobuffalo/buffalo.(Resource).Create-fm
PUT    | /user/{user_id}      | **userUpdatePath** | github.com/gobuffalo/buffalo.(Resource).Update-fm

as you may see most of the routes share the path with another one, so in order to differentiate the route function on the view i set a custom name for some of them, do you think this approach is ok for the resources ?

**Comment by markbates** [comment]
I'll review it all tomorrow, but I liked the way it you had it before, which was it was ok to have the same name if it produced the same URL.

**Comment by apaganobeleno** [comment]
Cool, thats less code which is my favorite flavor :D, i'll keep it as it was (without the dupes), thanks @markbates

**Comment by markbates** [comment]
@apaganobeleno is this ready for review again?

**Comment by apaganobeleno** [comment]
@markbates yes, its ready to be reviewed.

**Comment by markbates** [comment]
Can you add the route names to the `404`, `500`, and `index.html` pages?

Also, it would be great if we could update all the resource generator stuff to use the path functions as well. :)

**Comment by apaganobeleno** [comment]
@markbates i think i covered 404, 500, grift and index.html but i'll double-check, also will look into those resource generators, thanks @markbates !

**Comment by markbates** [comment]
Resource templates aren't being generated correctly.

```
$ buffalo g resource users name
$ buffalo db migrate
```

http://localhost:3000/users:
```
expected next token to be ), got : instead
no prefix parse function for : found
no prefix parse function for ) found
expected next token to be ), got : instead
no prefix parse function for : found
no prefix parse function for ) found
expected next token to be ), got : instead
no prefix parse function for : found
no prefix parse function for ) found
error inside of calling function
```

templates/users/index.html:
```erb
            <a href="<%= UserPath(users_id: user.ID) %>" class="btn btn-info">View</a>
            <a href="<%= UserEditPath(users_id: user.ID) %>" class="btn btn-warning">Edit</a>
            <a href="<%= UserPath(users_id: user.ID) %>" data-method="DELETE" data-confirm="Are you sure?" class="btn btn-danger">Destroy</a>
```

**Comment by apaganobeleno** [comment]
Hey @markbates i got this error after fixing the plush syntax:
```
form_for(pet, {action:petsPath(), method:POST, errors:errors}) { 
  return partial(pets/form.html);
  <a href="return petsPath();" class="btn btn-warning" data-confirm="Are you sure?">Cancel</a>
 }  (reflect.Value) is an invalid function
error inside of calling function
github.com/markbates/pop.(*Connection).Transaction.func1
	/Users/antoniopagano/go/src/github.com/markbates/pop/connection.go:107
github.com/markbates/pop.(*postgresql).Lock
	/Users/antoniopagano/go/src/github.com/markbates/pop/postgresql.go:150
github.com/markbates/pop.(*Connection).Transaction
	/Users/antoniopagano/go/src/github.com/markbates/pop/connection.go:110
github.com/gobuffalo/buffalo/middleware.glob..func1.1.1
	/Users/antoniopagano/go/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:29
github.com/gobuffalo/buffalo.RequestLoggerFunc.func1
	/Users/antoniopagano/go/src/github.com/gobuffalo/buffalo/request_logger.go:48
github.com/gobuffalo/buffalo.(*App).handlerToHandler.func1
	/Users/antoniopagano/go/src/github.com/gobuffalo/buffalo/handler.go:71
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1942
github.com/gorilla/mux.(*Router).ServeHTTP
	/Users/antoniopagano/go/src/github.com/gorilla/mux/mux.go:114
github.com/markbates/refresh/refresh/web.ErrorChecker.func1
	/Users/antoniopagano/go/src/github.com/markbates/refresh/refresh/web/web.go:23
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1942
github.com/gobuffalo/buffalo.(*App).ServeHTTP
	/Users/antoniopagano/go/src/github.com/gobuffalo/buffalo/app.go:40
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2568
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1825
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197
```

any idea of what can this be ?

**Comment by apaganobeleno** [comment]
Ahh! my sample app doesn't have `form_for`:D

**Comment by apaganobeleno** [comment]
@markbates this one is ready

**Comment by markbates** [comment]
I feel like this route:

```
GET    | /talks/new                | newTalksPath     | github.com/papercall/rome/actions.TalksResource.New
```

Should be called `newTalkPath` instead of `newTalksPath` since I'm only create a singular talk.

Also, with a resource, I have `newTalksPath` and talkEditPath`, I think we should standardize on where the extra word is placed. I vote for the beginning, so `newTalkPath` and `editTalkPath`. I can be persuaded either way.

**Comment by apaganobeleno** [comment]
Agreed, i'll work on this one and get back to you, thanks @markbates

**Comment by markbates** [comment]
Other than that it looks great!!

**Comment by apaganobeleno** [comment]
@markbates this one is all set :) moved `newTalksPath` to be `newTalkPath` and `talkEditPath` to be `editTalkPath`.

**Comment by markbates** [comment]
@apaganobeleno you're still generating resources with the old path names.

```
<a href="<%= newUsersPath() %>" class="btn btn-primary">Create New User</a>
```

```
<a href="<%= userEditPath({ user_id: user.ID }) %>" class="btn btn-warning">Edit</a>
```

**Comment by apaganobeleno** [comment]
oh boy! i completely forget (again) about that, sorry, i'm thinking we need to add some more unit/integration tests for the resource generation, its too easy to miss something when changing other parts of buffalo (also i know it should be very tedious for you to check all those) WDTY ?

I already fixed the links you mentioned thanks @markbates

**Comment by markbates** [comment]
Yeah, we need better resources testing. I think we need to examine our whole testing approach to be honest.

**Comment by markbates** [comment]
Major errors :(

```
<h1>Users</h1>

<p>
  <a href="<%= new<no value>Path() %>" class="btn btn-primary">Create New User</a>
</p>

<table class="table table-striped">
  <thead>
  <th>Name</th>
    <th>&nbsp;</th>
  </thead>
  <tbody>
    <%= for (user) in users { %>
      <tr>
      <td><%= user.Name %></td>
        <td>
          <div class="pull-right">
            <a href="<%= userPath({ user_id: user.ID }) %>" class="btn btn-info">View</a>
            <a href="<%= edit<no value>Path({ user_id: user.ID }) %>" class="btn btn-warning">Edit</a>
            <a href="<%= userPath({ user_id: user.ID }) %>" data-method="DELETE" data-confirm="Are you sure?" class="btn btn-danger">Destroy</a>
          </div>
        </td>
      </tr>
    <% } %>
  </tbody>
</table>
```

Notice the `<no value>` strings in there?

**Comment by markbates** [comment]
Here is my basic smoke test so you can repeat:

```
buffalo new -f coke
cd coke
buffalo setup -d
buffalo g resource users name
buffalo db migrate
buffalo t routes
buffalo dev
```

Then I start hitting pages.

**Comment by apaganobeleno** [comment]
Thanks Mark for all the patience with this one, that smoke script helped me a lot, maybe once we integrate the tests into the resource generator those tests could serve us to ensure we're not breaking anything when generating resources.

**Comment by markbates** [comment]
YAY!!!!!

**Comment by sio4** [comment]
How can I rename a named route for the Resources? My situation is:
- I generated a resource using `buffalo g resource...`
- I made a group for adding specific middleware to a group of resources (for example /admin/users)
- after then, route name was changed (group name was added)

Can I preserve the name of routes for resources using something lilke `.Name("usersPath")`?

**Pull request merged**
