### PR TITLE
Add Prefix to RootPath (BaseUrl)

### PR DESCRIPTION
**Pull request by SantoDE**
This one adds some sort of BasePath functionality to buffalo. It just appends the app.Prefix to the rootPath if set

### CODE REVIEW

**Comment by markbates** [comment]
@SantoDE let me know when you remove the WIP on this and want it reviewed.

**Comment by apaganobeleno** [comment]
@markbates i think he pushed this one so i can look at an issue he is having with the `rootPath`. @SantoDE i applied these changes to my local `development` branch and calling the `rootPath()` function from my sample app works ok, can you share a bit more details from the app you're building, maybe like how are you calling the rootPath function from your views ?

**Comment by SantoDE** [comment]
Updated and CI green. Happy for your review @markbates

**Comment by markbates** [comment]
I would love to see `ServeFiles` create a new helper.

**Comment by SantoDE** [comment]
I can do that, but what would be the gain? We have a rootPath already so why have two?

**Comment by markbates** [comment]
`<%= rootPath() %>/assets/images/foo.png` is very clunky. 

I would love to see `assetsPath("images/foo.png")`, or with a prefix `fooAssetsPath("images/foo.png")`.

**Comment by markbates** [comment]
@SantoDE the tests for this appear to be failing. can you please take a look?

**Comment by markbates** [comment]
@santode can you please look into the failing tests? I'd love to merge this.

**Comment by markbates** [comment]
@SantoDE I figured out what the problem was with your tests. It wasn't your code that was the problem. The route helper code was wrong. It was creating a new "root" helper for each new group or resource, so it was overriding the previous one. 

I fixed it here https://github.com/gobuffalo/buffalo/pull/572

**Pull request closed without merging**
