### PR TITLE
updated contributers list

### PR DESCRIPTION
**Pull request by markbates**

### CODE REVIEW

**Comment by bscott** [comment]
think you forgot someone ;)

**Comment by markbates** [comment]
@bscott for some reason you don't show up in the contributors tab in GitHub. I use a script that pulls out the committers names and sorts them by their volume. You have committed code, right? I feel like you have.

**Comment by bscott** [comment]
@markbates I did on the docs repo, but I do have a pending PR for buffalo that I'll push :)

**Comment by markbates** [comment]
That would be why! It just pulls in this repo's commits.

**Comment by markbates** [comment]
I really appreciate your help, just so you know.

**Pull request merged**
