### PR TITLE
updated router Group function to acount for Windows path cruft

### PR DESCRIPTION
**Pull request by schigh**
Refer to:
https://github.com/gobuffalo/buffalo/issues/258

### CODE REVIEW

**Comment by markbates** [comment]
@schigh it looks like the tests are failing.

**Comment by schigh** [comment]
Examining each failed test in Travis.  All my local invocations of `go test -race` are succeeding

**Comment by markbates** [comment]
Try running `docker build .` locally, that's what Travis runs.

**Comment by schigh** [comment]
The final update was much simpler...

**Comment by markbates** [comment]
lol. It's always that way. :)

Thanks!

**Pull request merged**
